default_provider: "openai"
providers:
  claude:
    provider: "anthropic"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key: "${CLAUDE_API_KEY}"
    model_name: "claude-3-5-sonnet-20241022"
    max_tokens: 4000
    temperature: 0.1
    timeout: "60s"
    retry_attempts: 3
    retry_delay: "1s"
    input_adapter: "claude_input_adapter"
    output_parser: "claude_extractor"
    prompt_formatter: "claude"
    parameters:
      system: "You are an OpenShift audit query specialist."
      max_tokens: "4000"
      temperature: "0.1"
      top_p: "0.9"
      top_k: "40"

  # OpenAI GPT-4 - Alternative provider for audit queries
  openai:
    provider: "openai"
    endpoint: "https://api.openai.com/v1/chat/completions"
    api_key: "${OPENAI_API_KEY}"
    model_name: "gpt-4"
    max_tokens: 4000
    temperature: 0.1
    timeout: "60s"
    retry_attempts: 3
    retry_delay: "1s"
    input_adapter: "openai_input_adapter"
    output_parser: "openai_extractor"
    prompt_formatter: "openai"
    parameters:
      system: "You are an OpenShift audit query specialist."
      max_tokens: "4000"
      temperature: "0.0"
      presence_penalty: "0.0"   # OpenAI-specific knobs (mapped if present)
      frequency_penalty: "0.0"
      response_format: "json_object"

  # Local Llama 3.1 - For offline/air-gapped environments
  local_llama:
    provider: "ollama"          # Non-Anthropic/OpenAI -> uses Generic provider path
    endpoint: "http://localhost:11434"
    api_key: ""                 # Often empty for local models
    model_name: "llama3.1:8b"
    max_tokens: 4000
    temperature: 0.1
    timeout: "60s"
    retry_attempts: 3
    retry_delay: "1s"
    input_adapter: "ollama_input_adapter"
    output_parser: "generic_extractor"
    prompt_formatter: "generic"
    parameters:
      system: "You are an OpenShift audit query specialist."
      max_tokens: "4000"
      temperature: "0.1"
      top_p: "0.9"
      top_k: "40"

  # Mistral 7B - Alternative local model
  local_mistral:
    provider: "ollama"
    endpoint: "http://localhost:11434"
    api_key: ""
    model_name: "mistral:7b"
    max_tokens: 4000
    temperature: 0.1
    timeout: "60s"
    retry_attempts: 3
    retry_delay: "1s"
    input_adapter: "ollama_input_adapter"
    output_parser: "generic_extractor"
    prompt_formatter: "generic"
    parameters:
      system: "You are an OpenShift audit query specialist."
      max_tokens: "4000"
      temperature: "0.1"
      top_p: "0.9"
      top_k: "40"

  # User-provided model - For custom/enterprise models
  user_model:
    provider: "generic"         # Use this for custom or enterprise gateways
    endpoint: "http://localhost:8080"
    api_key: ""
    model_name: "custom-model"
    max_tokens: 4000
    temperature: 0.1
    timeout: "60s"
    retry_attempts: 3
    retry_delay: "1s"
    input_adapter: "generic_input_adapter"
    output_parser: "generic_extractor"
    prompt_formatter: "generic_formatter"
    parameters:
      system: "You are an OpenShift audit query specialist."
      max_tokens: "4000"
      temperature: "0.1"

# Model capabilities and constraints
capabilities:
  # Maximum query length for input processing; requests longer than this should be trimmed upstream
  max_query_length: 1000
  
  # Maximum response length for output processing; used to inform prompt design and validation
  max_response_length: 2000
  
  # Supported log sources for OpenShift audit queries (validators may enforce these)
  supported_log_sources:
    - "kube-apiserver"
    - "openshift-apiserver"
    - "oauth-server"
    - "oauth-apiserver"
  
  # Supported HTTP verbs for audit filtering
  supported_verbs:
    - "get"
    - "list"
    - "create"
    - "update"
    - "patch"
    - "delete"
  
  # Supported Kubernetes resources (not exhaustive; common high-signal resources listed)
  supported_resources:
    - "pods"
    - "services"
    - "secrets"
    - "configmaps"
    - "namespaces"
    - "deployments"
    - "customresourcedefinitions"
    - "clusterroles"
    - "clusterrolebindings"
    - "rolebindings"
    - "serviceaccounts"
    - "persistentvolumeclaims"
    - "networkpolicies"
    - "validatingwebhookconfigurations"
    - "mutatingwebhookconfigurations"

# Safety and validation settings
safety:
  # Forbidden patterns that should be rejected by validators and/or prompts
  forbidden_patterns:
    - "rm -rf"
    - "delete --all"
    - "system:admin"
    - "drop database"
    - "format c:"
    - "shutdown"
    - "reboot"
  
  # Timeframe limits for audit queries; guardrails for unbounded data scans
  timeframe_limits:
    max_days_back: 90
    default_limit: 20
    max_limit: 1000
  
  # Required fields for valid audit queries; parsers should aim to produce these
  required_fields:
    - "log_source"
  
  # User patterns to exclude by default; reduces noise from system identities
  default_exclude_users:
    - "system:"
    - "kube-"
    - "openshift-"
