# Enhanced Validation Rules Configuration (Unit 3)
# This file defines comprehensive validation rules for OpenShift audit query safety and advanced analysis

# Rule Engine Configuration
rule_engine:
  parallel_execution: true
  worker_pool_size: 4
  rule_timeout_seconds: 30
  dependency_resolution: true

# Advanced Analysis Rules
advanced_analysis:
  enabled: true
  max_threshold_value: 10
  allowed_analysis_types:
    # Core analysis types
    - "multi_namespace_access"
    - "excessive_reads"
    - "privilege_escalation"
    - "anomaly_detection"
    - "correlation"
    - "behavioral_analysis"
    - "statistical_analysis"
    
    # Advanced threat hunting & APT detection
    - "apt_reconnaissance_detection"
    - "c2_communication_detection"
    - "lateral_movement_detection"
    - "data_exfiltration_detection"
    - "living_off_the_land_detection"
    - "supply_chain_attack_detection"
    - "persistence_mechanism_detection"
    - "defense_evasion_detection"
    - "credential_harvesting_detection"
    - "impact_destruction_detection"
    
    # Behavioral analytics & machine learning
    - "statistical_user_behavior_analysis"
    - "time_series_anomaly_detection"
    - "ml_feature_vector_generation"
    - "percentile_based_anomaly_detection"
    - "graph_based_network_analysis"
    - "behavioral_cohort_clustering"
    - "seasonal_cyclic_pattern_detection"
    - "predictive_resource_access_modeling"
    - "multi_dimensional_behavioral_risk_profiling"
    - "ensemble_orchestration_anomaly_detection"
    
    # Multi-source intelligence & correlation
    - "multi_source_credential_compromise_correlation"
    - "supply_chain_multi_source_correlation"
    - "multi_source_timeline_reconstruction"
    - "account_takeover_multi_source_detection"
    - "image_stream_deployment_compliance_correlation"
    - "multi_source_failure_pattern_investigation"
    - "node_container_orchestration_correlation"
    - "cross_platform_identity_provider_correlation"
    - "security_policy_access_pattern_correlation"
    - "comprehensive_incident_reconstruction"
    
    # Compliance & governance automation
    - "sox_compliance_privileged_access_audit"
    - "pci_dss_compliance_monitoring"
    - "gdpr_data_processing_audit"
    - "hipaa_phi_compliance_audit"
    - "regulatory_compliance_dashboard"
    - "data_retention_compliance_automation"
    - "segregation_of_duties_violation_monitoring"
    - "sox_404_financial_controls_tracking"
    - "automated_compliance_reporting_dashboard"
    - "data_classification_compliance_validation"
    
    # Incident response & digital forensics
    - "comprehensive_incident_correlation"
    - "container_breakout_digital_forensics"
    - "security_incident_attribution_analysis"
    - "digital_evidence_collection_analysis"
    - "attack_kill_chain_reconstruction"
    - "network_ioc_service_mesh_analysis"
    - "automated_incident_response_orchestration"
    - "memory_forensics_container_runtime_analysis"
    - "comprehensive_incident_documentation"
    - "post_incident_learning_analysis"
    
    # Risk assessment & security metrics
    - "comprehensive_risk_score_calculation"
    - "security_posture_dashboard_generation"
    - "security_control_effectiveness_analysis"
    - "vulnerability_assessment_correlation"
    - "security_maturity_index_calculation"
    - "executive_security_scorecard_generation"
    - "security_control_gap_analysis"
    - "predictive_risk_modeling"
    - "comprehensive_security_program_assessment"
    - "comprehensive_security_analytics_report"
    
    # Intermediate query patterns
    - "rapid_create_delete_pattern"
    - "service_account_ip_analysis"
    - "system_file_access_monitoring"
    - "bulk_deletion_detection"
    - "impersonation_detection"
    - "multi_namespace_coordination"
    - "oauth_token_security_analysis"
    - "user_session_pattern_analysis"
    - "user_behavior_anomaly_detection"
    - "administrative_workflow_tracking"
    - "sensitive_data_access_tracking"
    - "privilege_management_tracking"
    - "oauth_client_access_monitoring"
    - "user_command_execution_tracking"
    - "application_management_tracking"
    - "storage_access_tracking"
    - "traffic_management_tracking"
    - "brute_force_detection"
    - "password_spraying_detection"
    - "oauth_api_auth_failure_analysis"
    - "k8s_api_auth_failure_tracking"
    - "user_agent_pattern_analysis"
    - "geographic_distribution_analysis"
    - "system_account_attack_detection"
    - "after_hours_attack_detection"
    - "token_abuse_detection"
    - "reconnaissance_detection"
    - "container_security_investigation"
    - "oauth_token_manipulation_investigation"
    - "privilege_escalation_chain_detection"
    - "suspicious_filesystem_investigation"
    - "security_context_escalation_investigation"
    - "build_deployment_security_investigation"
    - "webhook_bypass_investigation"
    - "certificate_secret_forensics"
    - "cross_namespace_security_investigation"
    - "maintenance_window_analysis"
    - "peak_hours_resource_spike_analysis"
    - "shift_change_auth_clustering"
    - "weekend_holiday_analysis"
    - "off_hours_oauth_compliance_monitoring"
    - "rapid_operation_automation_detection"
    - "periodic_build_deployment_pattern_analysis"
    - "temporal_auth_resource_correlation"
    - "maintenance_window_node_audit_monitoring"
    - "service_account_temporal_pattern_analysis"
    - "rbac_violation_privilege_escalation_analysis"
    - "cluster_admin_privilege_monitoring"
    - "service_account_permission_abuse_detection"
    - "oauth_client_permission_scope_investigation"
    - "namespace_permission_boundary_analysis"
    - "custom_resource_permission_analysis"
    - "security_context_constraint_violation_monitoring"
    - "privilege_escalation_rolebinding_analysis"
    - "impersonation_identity_spoofing_investigation"
    - "admission_controller_authorization_analysis"
    - "cross_source_correlation"
    - "timeline_reconstruction"
    - "evidence_correlation"
  kill_chain_phases:
    - "reconnaissance"
    - "weaponization" 
    - "delivery"
    - "exploitation"
  max_group_by_fields: 5

# Time Windows Configuration (Single Source of Truth)
time_windows:
  # Comprehensive time windows consolidating all actual usage from test queries
  allowed_time_windows:
    # Short durations (analysis/correlation)
    - "1_minute"
    - "5_minutes" 
    - "10_minutes"
    - "15_minutes"
    - "30_minutes"
    - "1_hour"
    - "2_hours"
    - "4_hours"
    - "6_hours"
    - "8_hours"
    - "12_hours"
    - "24_hours"
    
    # Extended durations (baseline/historical analysis)
    - "48_hours"
    - "72_hours"
    - "7_days"
    - "14_days"
    - "30_days"
    - "168_hours"  # 7 days in hours format
  
  # Specific correlation windows for multi-source analysis
  allowed_correlation_windows:
    - "1_minute"
    - "5_minutes"
    - "15_minutes"
    - "30_minutes"
    - "1_hour"
    - "4_hours"
    - "24_hours"
  
  # Baseline windows for behavioral analysis
  allowed_baseline_windows:
    - "7_days"
    - "14_days"
    - "30_days"
    - "60_days"
    - "90_days"

# Behavioral Analytics Rules
behavioral_analytics:
  enabled: true
  allowed_risk_factors:
    - "privilege_level"
    - "resource_sensitivity"
    - "timing_anomaly"
    - "access_pattern"
  max_risk_factors: 10
  baseline_window_limits:
    min_baseline_days: 7
    max_baseline_days: 90
  anomaly_threshold_limits:
    min: 0.1
    max: 10.0

# Sort Configuration (Single Source of Truth)
sort_configuration:
  allowed_sort_fields:
    - "timestamp"
    - "username"
    - "resource"
    - "verb"
    - "count"
    - "risk_score"
    - "frequency"
    - "severity"
    - "namespace"
    - "auth_decision"
    - "response_code"
    - "source_ip"
    - "user_agent"
    - "request_uri"
    - "object_name"
    - "audit_id"
    - "stage"
  allowed_sort_orders:
    - "asc"
    - "desc"

# Compliance Rules
compliance:
  enabled: true
  allowed_standards:
    - "SOX"
    - "PCI-DSS"
    - "GDPR"
    - "HIPAA"
    - "ISO27001"
  max_standards: 5
  max_controls: 10
  min_retention_days: 365
  max_audit_gap_hours: 24

# Multi-Source Rules
multi_source:
  enabled: true
  max_sources: 5
  max_correlation_fields: 10
  max_correlation_complexity: 100
  
# Consolidated Input Validation (replaces scattered safety_rules and sanitization sections)
input_validation:
  enabled: true
  
  # Required Fields Validation (consolidated from safety_rules.required_fields)
  required_fields:
    mandatory: ["log_source"]
    conditional: []
  
  # Character & Format Validation (consolidated from sanitization character/format rules)
  character_validation:
    max_query_length: 10000
    max_pattern_length: 500
    forbidden_chars: ["<", ">", "&", "\"", "'", "`", "|", ";", "$"]
    valid_regex_pattern: "^[a-zA-Z0-9\\-_\\*\\.\\?\\+\\[\\]\\{\\}\\(\\)\\|\\\\/\\s]+$"
    valid_ip_pattern: "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
  
  # Security Pattern Validation (consolidated from safety_rules.forbidden_patterns)
  security_patterns:
    forbidden_patterns:
      - "system:admin"
      - "system:masters"
      - "cluster-admin"
      - "delete --all"
      - "delete --force"
      - "privileged: true"
      - "hostNetwork: true"
      - "runAsUser: 0"
      - "oc adm policy add-cluster-role-to-user cluster-admin"
      - "oc delete project --all"
      - "service-account-token"
      - "bearer token"
  
  # Field Value Validation (consolidated from safety_rules allowed lists)
  field_values:
    allowed_log_sources:
      - "kube-apiserver"
      - "openshift-apiserver"
      - "oauth-server"
      - "oauth-apiserver"
      - "node-auditd"
    allowed_verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "delete"
      - "watch"
      - "impersonate"
    allowed_resources:
      - "pods"
      - "services"
      - "deployments"
      - "configmaps"
      - "secrets"
      - "namespaces"
      - "serviceaccounts"
      - "roles"
      - "rolebindings"
      - "clusterroles"
      - "clusterrolebindings"
      - "customresourcedefinitions"
      - "persistentvolumeclaims"
      - "networkpolicies"
      - "events"
      - "nodes"
      - "routes"
      - "builds"
      - "imagestreams"
      - "projects"
      - "users"
      - "groups"
      - "oauthclients"
      - "securitycontextconstraints"
    allowed_auth_decisions:
      - "allow"
      - "error"
      - "forbid"
    allowed_response_status:
      - "200"
      - "201"
      - "204"
      - "400"
      - "401"
      - "403"
      - "404"
      - "409"
      - "422"
      - "500"
      - "502"
      - "503"
      - "504"
  
  # Performance Limits (consolidated from sanitization performance rules)
  performance_limits:
    max_result_limit: 50
    max_array_elements: 15
    max_days_back: 90
    allowed_timeframes:
      - "today"
      - "yesterday" 
      - "1_hour_ago"
      - "6_hours_ago"
      - "12_hours_ago"
      - "1_day_ago"
      - "3_days_ago"
      - "7_days_ago"
      - "30_days_ago"
      - "90_days_ago"

